version: '3.8'

services:
  visitorinfoapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5221:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
